version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:16

jobs:
  run-playwright-script:
    executor: default
    parallelism: 100
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget -qO- https://deb.nodesource.com/setup_16.x | sudo bash -
            sudo apt-get install -y nodejs
            sudo npm install playwright
            sudo npx playwright install
            sudo apt-get install -y libx11-xcb1 libxrandr2 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libgtk-3-0 libgdk-pixbuf2.0-0 libasound2 libdbus-1-3
      - run:
          name: Run Playwright Script
          command: node run.js

workflows:
  version: 2
  test:
    jobs:
      - run-playwright-script
